<?php

namespace App\Controller\Admin;

use App\Entity\Address;
use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Form\FormBuilderInterface;

class UserCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {

        return User::class;
    }


    public function configureFields(string $pageName): iterable
    {
       yield IdField::new('ID')
           ->onlyOnIndex();
       yield TextField::new('FullName',label: 'Nom complet');
       yield AssociationField::new('address',label: 'Adresse')
           ->hideOnForm();
       yield TextField::new('phone',label: 'Téléphone');
       yield TextField::new('email',label: 'Email');
       yield DateTimeField::new('created_at',label: 'Créé le')
           ->onlyOnIndex();
       yield ArrayField::new('roles',label: 'Autorisations')
           ->hideOnIndex();


    }

    public function configureActions(Actions $actions) : Actions{
         return parent::configureActions($actions); // TODO: Change the autogenerated stub
    }

}
